version: 0.2

phases:
  build:
    commands:
      - mkdir build
      - pip install -r src/${PROJECT_NAME}/requirements.txt --target src/${PROJECT_NAME}
      - zip -r build/${PROJECT_NAME}.zip src/${PROJECT_NAME}
artifacts:
  files:
    - "build/${PROJECT_NAME}.zip"
  name: "${PROJECT_NAME}-$(date +%Y-%m-%d)"
