version: 0.2

phases:
  build:
    commands:
      - mkdir build
      - pip install -r src/hello-world/requirements.txt --target src/hello-world
      - zip -r build/foo-$(git rev-parse --short HEAD).zip src/hello-world
      - SOURCE="foo-$(git rev-parse --short HEAD).zip" && cp build/$SOURCE build/foo-$(sha256sum $SOURCE | xxd -r -p | base64).zip
      - env
artifacts:
  files:
    - 'build/*.zip'
  name: foo-$(date +%Y-%m-%d) 
