version: 0.2

phases:
  build:
    commands:
      - mkdir build
      - pip install -r src/hello-world/requirements.txt --target src/hello-world
      - zip -r build/foo-$(git rev-parse --short HEAD).zip src/hello-world
      - env
artifacts:
  files:
    - 'build/*.zip'
  name: foo-$(date +%Y-%m-%d) 
